# Site settings
title: Pinal Bhatt's Blog
tagline: Learning endeavor for ever…
pgTitleSufix: Pinal Bhatt's Blog, Learning endeavor for ever…
metaKeywords: Pinal, Bhatt, Pinal Bhatt, Pinal Bhatt's Blog, PBDesk, PBDesk.io,
  PBDesk.com, blog.pbdesk.com, Angular, AngularJS, NodeJS, ASP.Net, MVC, Javascript
email: self@pbdesk.io
description: > # this means to ignore newlines until "baseurl:"
  Pinal Bhatt's Blog, Learning endeavor for ever…
  On this blog you'll find interesting posts, articles, tutorials, news updates and links on Microsoft.Net,
  ASP.NET, MVC, WebAPIs, C#, Windows10, JavaScript, AngularJS, NodeJS, Social Media, Mobiles, Science & Technology
  and other random thoughts and opinions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.pbdesk.io" # the base hostname & protocol for your site
twitter_username: PBDesk
github_username:  PBDesk

permalink: /:year/:month/:title
comments: true
# Build settings
markdown: kramdown

category_archive:
  path: category

monthly_archive:
  path: archive
